# Generated by Django 5.2 on 2025-04-09 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('satruday', 'Satruday')], max_length=10)),
                ('class_time', models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('8:00AM', '8:00AM'), ('9:00AM', '9:00AM'), ('10:00AM', '10:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10)),
                ('available', models.BooleanField()),
                ('staff_member_id', models.ForeignKey(db_column='staff_member_id', on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember')),
            ],
        ),
    ]
