# Generated by Django 5.2 on 2025-04-09 21:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffavailability_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffavailability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='staffavailability',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='staffavailability',
            name='day',
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('8:00AM', '8:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('8:30AM', '8:30AM'), ('10:00AM', '10:00AM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('9:00AM', '9:00AM'), ('10:00AM', '10:00AM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('8:00AM', '8:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('8:00AM', '8:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('6:00AM', '6:00AM'), ('7:00AM', '7:00AM'), ('12:00PM', '12:00PM'), ('5:00PM', '5:00PM'), ('6:30PM', '6:30PM')], max_length=10), blank=True, null=True, size=None),
        ),
    ]
